In [1]:
!pip install nltk

In [2]:
### IMPORTING ALL THE NECESSARY LIBRARIES 
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [4]:
from nltk.stem import WordNetLemmatizer

# Download the WordNet corpus if not already downloaded
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [5]:
import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer
from textblob import TextBlob

C:\Users\ASUS\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\ASUS\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [7]:
pip install --upgrade openpyxl


Note: you may need to restart the kernel to use updated packages.


In [8]:
## IMPORTING THE DATASET

df = pd.read_excel("A_II_Emotion_Data_Student_Copy_Final.xlsx")

In [9]:
df.head()

ID_ brand_name_ country_  star_rating_ emotions_  \
0     ID1          Z_       US             5       NaN   
1    ID10          Z_       GB             5       NaN   
2   ID100          H_      FRI             5       joy   
3  ID1000          H_       GB             1      fear   
4  ID1001          H_       GB             1       NaN   

                                       text_reviews_  
0  Fast shipping! All cloths was finally fits wel...  
1  Just wanted to say how delighted I was with th...  
2  My order took 6 days with a snow day and a wee...  
3  Wouldnt give them no stars. I ordered a coat 4...  
4  Parcel never arrived. Chasing for a refund for...

In [10]:
df.shape

(5722, 6)

In [11]:
df["text_reviews_"].head()

0    Fast shipping! All cloths was finally fits wel...
1    Just wanted to say how delighted I was with th...
2    My order took 6 days with a snow day and a wee...
3    Wouldnt give them no stars. I ordered a coat 4...
4    Parcel never arrived. Chasing for a refund for...
Name: text_reviews_, dtype: object

### LOWER CASE 

In [12]:
### CONVERTING THE TEXT REVIEW COLUMN INTO LOWER CASE 
# Assuming 'df' is your DataFrame and 'review' is the column containing text reviews
df['text_reviews_'] = df['text_reviews_'].str.lower()


In [13]:
df['text_reviews_']

0       fast shipping! all cloths was finally fits wel...
1       just wanted to say how delighted i was with th...
2       my order took 6 days with a snow day and a wee...
3       wouldnt give them no stars. i ordered a coat 4...
4       parcel never arrived. chasing for a refund for...
                              ...                        
5717    iãƒâ¯ã‚â¾ã‚æ’ãƒâ£ã‚æ’ã‚â£ãƒâ¯ã‚â¾ã‚æ’ãƒâ¯ã‚â½ã...
5718    i wanted to change the delivery location of my...
5719    waiting since 24/14/2022. i believe the sent m...
5720    who do you complain to about late deliveries f...
5721    placed an order on the 24th november. h_ alert...
Name: text_reviews_, Length: 5722, dtype: object

In [14]:
import pandas as pd
import re

def check_for_punctuation(text):
    # Define a regular expression pattern to match punctuation and special symbols
    pattern = r'[\W_]'  # Matches any non-word character or underscore

    # Search for the pattern in the text
    matches = re.findall(pattern, text)
    
    return matches

# Assuming 'df' is your DataFrame and 'review' is the column containing text reviews
df['punctuation'] = df['text_reviews_'].apply(check_for_punctuation)


In [15]:
df['punctuation']

0                    [ , !,  ,  ,  ,  ,  ,  , !,  ,  , !]
1       [ ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , ...
2       [ ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , ...
3       [ ,  ,  ,  , .,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , ...
4       [ ,  , .,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , -, ...
                              ...                        
5717    [ƒ, ¯, ‚, ‚, ’, ƒ, £, ‚, ’, ‚, £, ƒ, ¯, ‚, ‚, ...
5718    [ ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , ...
5719    [ ,  , /, /, .,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , ...
5720    [ ,  ,  ,  ,  ,  ,  ,  ,  ,  ,  , ?, ?,  ,  , ...
5721    [ ,  ,  ,  ,  ,  , .,  , _,  ,  ,  ,  ,  ,  , ...
Name: punctuation, Length: 5722, dtype: object

In [16]:
import pandas as pd
import re

def check_for_irrelevant_characters(text):
    # Define a regular expression pattern to match irrelevant characters
    pattern = r'[^a-zA-Z0-9\s]'  # Matches any character that is not a letter, digit, or whitespace

    # Search for the pattern in the text
    matches = re.findall(pattern, text)
    
    return matches

# Assuming 'df' is your DataFrame and 'review' is the column containing text reviews
df['irrelevant_characters'] = df['text_reviews_'].apply(check_for_irrelevant_characters)


In [17]:
df['irrelevant_characters']

0                                               [!, !, !]
1                                            [_, ., ., .]
2                                                     [.]
3                                         [., ., ., ., .]
4                                            [., -, ., .]
                              ...                        
5717    [ã, ƒ, â, ¯, ã, ‚, â, ¾, ã, ‚, æ, ’, ã, ƒ, â, ...
5718    [., ., ã, ƒ, â, ¯, ã, ‚, â, ¾, ã, ‚, æ, ’, ã, ...
5719                                      [/, /, ., ., .]
5720                                      [?, ?, ., ., !]
5721                                [., _, ., &, ., ., .]
Name: irrelevant_characters, Length: 5722, dtype: object

In [18]:
import pandas as pd
import re
import string

def clean_text(text):
    # Define a regular expression pattern to match irrelevant characters
    pattern = r'[^a-zA-Z0-9\s]'  # Matches any character that is not a letter, digit, or whitespace
    punctuation_pattern = r'[{}]'.format(re.escape(string.punctuation))  # Matches any punctuation character
    
    # Concatenate all characters in the list into a single string
    text = ''.join(text)
    
    # Remove irrelevant characters and punctuation using the patterns
    cleaned_text = re.sub(pattern, '', text)
    cleaned_text = re.sub(punctuation_pattern, '', cleaned_text)
    
    return cleaned_text

# Assuming 'df' is your DataFrame and 'text' is the column containing lists of characters
df['cleaned_text'] = df['text_reviews_'].apply(clean_text)


In [19]:
# Assuming 'df' is your DataFrame and you've already cleaned the text and stored it in the 'cleaned_text' column
df['text_reviews_'] = df['cleaned_text']


In [20]:
df['text_reviews_']

0       fast shipping all cloths was finally fits well...
1       just wanted to say how delighted i was with th...
2       my order took 6 days with a snow day and a wee...
3       wouldnt give them no stars i ordered a coat 4 ...
4       parcel never arrived chasing for a refund for ...
                              ...                        
5717    id have given 0 stars if i could if id have kn...
5718    i wanted to change the delivery location of my...
5719    waiting since 24142022 i believe the sent my o...
5720    who do you complain to about late deliveries f...
5721    placed an order on the 24th november h alerts ...
Name: text_reviews_, Length: 5722, dtype: object

In [21]:
# Assuming 'df' is your DataFrame
last_rows_text = df.iloc[-10:]['text_reviews_']  # Assuming you want to see the last 10 rows
print(last_rows_text)


5712    h x evri welcome to hellupdate 3 i called h cu...
5713    wating for wife to finish shopping   the worke...
5714    first time i ever ordered it took weeks to com...
5715    i received an item that was the wrong colour a...
5716    missing delivery with evri for over a week and...
5717    id have given 0 stars if i could if id have kn...
5718    i wanted to change the delivery location of my...
5719    waiting since 24142022 i believe the sent my o...
5720    who do you complain to about late deliveries f...
5721    placed an order on the 24th november h alerts ...
Name: text_reviews_, dtype: object


## To check if the text_review has removed the punctuation and irrelevant character 

In [22]:
# Assuming 'df' is your DataFrame and 'cleaned_text' is the column containing the cleaned text
original_text = df['text_reviews_']
cleaned_text = df['cleaned_text']

# Check if original_text and cleaned_text are equal
all_characters_removed = original_text.equals(cleaned_text)

if all_characters_removed:
    print("All punctuation and irrelevant characters have been successfully removed.")
else:
    print("Some punctuation or irrelevant characters may still be present.")


All punctuation and irrelevant characters have been successfully removed.


In [23]:
df['cleaned_text']= df['text_reviews_']

In [24]:
df['text_reviews_'].head()

0    fast shipping all cloths was finally fits well...
1    just wanted to say how delighted i was with th...
2    my order took 6 days with a snow day and a wee...
3    wouldnt give them no stars i ordered a coat 4 ...
4    parcel never arrived chasing for a refund for ...
Name: text_reviews_, dtype: object

In [25]:
# Assuming 'df' is your DataFrame and 'cleaned_text' is the column containing the cleaned text
original_text = df['text_reviews_'].iloc[5712:]



In [26]:
original_text

5712    h x evri welcome to hellupdate 3 i called h cu...
5713    wating for wife to finish shopping   the worke...
5714    first time i ever ordered it took weeks to com...
5715    i received an item that was the wrong colour a...
5716    missing delivery with evri for over a week and...
5717    id have given 0 stars if i could if id have kn...
5718    i wanted to change the delivery location of my...
5719    waiting since 24142022 i believe the sent my o...
5720    who do you complain to about late deliveries f...
5721    placed an order on the 24th november h alerts ...
Name: text_reviews_, dtype: object

In [27]:
df.columns

Index(['ID_', 'brand_name_', 'country_', 'star_rating_', 'emotions_',
       'text_reviews_', 'punctuation', 'irrelevant_characters',
       'cleaned_text'],
      dtype='object')

## REMOVING THE UNECESSARY COLUMN 

In [28]:
# Assuming 'df' is your DataFrame
columns_to_remove = ['punctuation', 'irrelevant_characters', 'cleaned_text']
df.drop(columns=columns_to_remove, inplace=True)


## TOKENIZATION 


In [29]:
import nltk
from nltk.tokenize import word_tokenize

# Download the punkt tokenizer model if not already downloaded
nltk.download('punkt')

# Tokenize function
def tokenize_text(text):
    return word_tokenize(text)

# Apply tokenization to the 'text' column
df['tokenized_text'] = df['text_reviews_'].apply(tokenize_text)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [30]:
df.columns

Index(['ID_', 'brand_name_', 'country_', 'star_rating_', 'emotions_',
       'text_reviews_', 'tokenized_text'],
      dtype='object')

In [31]:
df['tokenized_text']

0       [fast, shipping, all, cloths, was, finally, fi...
1       [just, wanted, to, say, how, delighted, i, was...
2       [my, order, took, 6, days, with, a, snow, day,...
3       [wouldnt, give, them, no, stars, i, ordered, a...
4       [parcel, never, arrived, chasing, for, a, refu...
                              ...                        
5717    [id, have, given, 0, stars, if, i, could, if, ...
5718    [i, wanted, to, change, the, delivery, locatio...
5719    [waiting, since, 24142022, i, believe, the, se...
5720    [who, do, you, complain, to, about, late, deli...
5721    [placed, an, order, on, the, 24th, november, h...
Name: tokenized_text, Length: 5722, dtype: object

In [32]:
df['tokenized_text'].head()

0    [fast, shipping, all, cloths, was, finally, fi...
1    [just, wanted, to, say, how, delighted, i, was...
2    [my, order, took, 6, days, with, a, snow, day,...
3    [wouldnt, give, them, no, stars, i, ordered, a...
4    [parcel, never, arrived, chasing, for, a, refu...
Name: tokenized_text, dtype: object

## STOPWORDS 


In [33]:


# Getting the list of English stop words
stop_words = set(stopwords.words('english'))

# Function to remove stop words from tokenized text
def remove_stop_words(tokens):
    return [word for word in tokens if word not in stop_words]

# Apply stop word removal to the 'tokenized_text' column
df['tokenized_text'] = df['tokenized_text'].apply(remove_stop_words)


In [34]:
df['tokenized_text']

0       [fast, shipping, cloths, finally, fits, well, ...
1       [wanted, say, delighted, friendly, helpful, st...
2       [order, took, 6, days, snow, day, weekend, hap...
3       [wouldnt, give, stars, ordered, coat, 4, weeks...
4       [parcel, never, arrived, chasing, refund, subs...
                              ...                        
5717    [id, given, 0, stars, could, id, known, evri, ...
5718    [wanted, change, delivery, location, item, wit...
5719    [waiting, since, 24142022, believe, sent, orde...
5720    [complain, late, deliveries, horrendous, compn...
5721    [placed, order, 24th, november, h, alerts, ord...
Name: tokenized_text, Length: 5722, dtype: object

## LEMMATISATION 

In [35]:

# Initialize the WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# Function to perform lemmatization on a list of tokens
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(token) for token in tokens]

# Apply lemmatization to the 'tokenized_text' column
df['tokenized_text'] = df['tokenized_text'].apply(lemmatize_tokens)


In [36]:
df['tokenized_text']

0       [fast, shipping, cloth, finally, fit, well, sa...
1       [wanted, say, delighted, friendly, helpful, st...
2       [order, took, 6, day, snow, day, weekend, happ...
3       [wouldnt, give, star, ordered, coat, 4, week, ...
4       [parcel, never, arrived, chasing, refund, subs...
                              ...                        
5717    [id, given, 0, star, could, id, known, evri, h...
5718    [wanted, change, delivery, location, item, wit...
5719    [waiting, since, 24142022, believe, sent, orde...
5720    [complain, late, delivery, horrendous, compnay...
5721    [placed, order, 24th, november, h, alert, orde...
Name: tokenized_text, Length: 5722, dtype: object

In [36]:
df.head()

ID_ brand_name_ country_  star_rating_ emotions_  \
0     ID1          Z_       US             5       NaN   
1    ID10          Z_       GB             5       NaN   
2   ID100          H_      FRI             5       joy   
3  ID1000          H_       GB             1      fear   
4  ID1001          H_       GB             1       NaN   

                                       text_reviews_  \
0  fast shipping all cloths was finally fits well...   
1  just wanted to say how delighted i was with th...   
2  my order took 6 days with a snow day and a wee...   
3  wouldnt give them no stars i ordered a coat 4 ...   
4  parcel never arrived chasing for a refund for ...   

                                      tokenized_text  
0  [fast, shipping, cloth, finally, fit, well, sa...  
1  [wanted, say, delighted, friendly, helpful, st...  
2  [order, took, 6, day, snow, day, weekend, happ...  
3  [wouldnt, give, star, ordered, coat, 4, week, ...  
4  [parcel, never, arrived, chasing, refund, subs...

In [37]:
df['emotions_'].unique()

array([nan, 'joy', 'fear', 'surprise', 'anger', 'neutral', 'disgust',
       'sadness'], dtype=object)

In [38]:
# Assuming 'df' is your DataFrame
df.drop(columns=['text_reviews_'], inplace=True)


In [39]:
df.head()

ID_ brand_name_ country_  star_rating_ emotions_  \
0     ID1          Z_       US             5       NaN   
1    ID10          Z_       GB             5       NaN   
2   ID100          H_      FRI             5       joy   
3  ID1000          H_       GB             1      fear   
4  ID1001          H_       GB             1       NaN   

                                      tokenized_text  
0  [fast, shipping, cloth, finally, fit, well, sa...  
1  [wanted, say, delighted, friendly, helpful, st...  
2  [order, took, 6, day, snow, day, weekend, happ...  
3  [wouldnt, give, star, ordered, coat, 4, week, ...  
4  [parcel, never, arrived, chasing, refund, subs...

In [40]:
!pip install transformers

In [41]:
from transformers import pipeline

In [42]:
def analyze_emotion(tokenized_text):
    # Assuming 'tokenized_text' is the column containing tokenized text in your DataFrame df
    model = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")  # download pre-trained emotion classification model
    label_score = model(tokenized_text.tolist())  # Convert the column to a list and pass it to the model
    return label_score


## SEMI SUPERVISED LEARNING 

In [51]:
import pandas as pd
import numpy as np
import re

import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.semi_supervised import LabelSpreading
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [43]:
df.head()

ID_ brand_name_ country_  star_rating_ emotions_  \
0     ID1          Z_       US             5       NaN   
1    ID10          Z_       GB             5       NaN   
2   ID100          H_      FRI             5       joy   
3  ID1000          H_       GB             1      fear   
4  ID1001          H_       GB             1       NaN   

                                      tokenized_text  
0  [fast, shipping, cloth, finally, fit, well, sa...  
1  [wanted, say, delighted, friendly, helpful, st...  
2  [order, took, 6, day, snow, day, weekend, happ...  
3  [wouldnt, give, star, ordered, coat, 4, week, ...  
4  [parcel, never, arrived, chasing, refund, subs...

In [44]:
unlabeled_data = df[df['emotions_'] == 'NaN'][['tokenized_text']]
unlabeled_data['emotions_'] = -1
print(unlabeled_data)

Empty DataFrame
Columns: [tokenized_text, emotions_]
Index: []


In [45]:
import numpy as np

# Filter rows with NaN values in the 'emotions_' column and select the 'tokenized_text' column
unlabeled_data = df[pd.isna(df['emotions_'])][['tokenized_text']]

# Assign the label -1 to the 'emotions_' column for unlabeled data
unlabeled_data['emotions_'] = -1

print(unlabeled_data)


                                         tokenized_text  emotions_
0     [fast, shipping, cloth, finally, fit, well, sa...         -1
1     [wanted, say, delighted, friendly, helpful, st...         -1
4     [parcel, never, arrived, chasing, refund, subs...         -1
5     [avoid, ordering, online, ordered, 12, day, ag...         -1
6     [awful, service, returning, item, booked, coll...         -1
...                                                 ...        ...
5717  [id, given, 0, star, could, id, known, evri, h...         -1
5718  [wanted, change, delivery, location, item, wit...         -1
5719  [waiting, since, 24142022, believe, sent, orde...         -1
5720  [complain, late, delivery, horrendous, compnay...         -1
5721  [placed, order, 24th, november, h, alert, orde...         -1

[5095 rows x 2 columns]


In [46]:
# Define labeled data as data where "Sentiment" is not missing
labeled_data = df[df['emotions_'].notna() & (df['emotions_'] != 'NaN')]

In [47]:
labeled_data

ID_ brand_name_ country_  star_rating_ emotions_  \
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
10    ID1007          H_       GB             1  surprise   
18    ID1014          H_       GB             1     anger   
25    ID1020          H_       GB             1   neutral   
...      ...         ...      ...           ...       ...   
5692   ID972          H_       US             1   sadness   
5695   ID975          H_       GB             1      fear   
5701   ID980          H_       GB             1     anger   
5711    ID99          H_       DE             5       joy   
5715   ID993          H_       GB             1     anger   

                                         tokenized_text  
2     [order, took, 6, day, snow, day, weekend, happ...  
3     [wouldnt, give, star, ordered, coat, 4, week, ...  
10    [went, h, glasgow, saturday, bought, kid, stuf...  
18    [trying, order, product, online, cost, option,...  
25                                          [use, evri]  
...                                                 ...  
5692  [dont, order, online, go, store, tooooo, much,...  
5695  [h, use, evri, formally, hermes, courier, lost...  
5701  [staff, westfield, stratford, rude, went, 2, 5...  
5711  [packet, came, weekim, super, satisfiedeveryth...  
5715  [received, item, wrong, colour, damaged, conta...  

[627 rows x 6 columns]

In [60]:
# Extract labels from labeled_data
y_labeled = labeled_data['emotions_']
y_unlabeled = unlabeled_data['emotions_']
X_labeled = labeled_data['tokenized_text']
X_unlabeled = unlabeled_data['tokenized_text']


In [61]:
print("y_labeled ",y_labeled )


y_labeled  2            joy
3           fear
10      surprise
18         anger
25       neutral
          ...   
5692     sadness
5695        fear
5701       anger
5711         joy
5715       anger
Name: emotions_, Length: 627, dtype: object


In [62]:
print("y_unlabeled",y_unlabeled)


y_unlabeled 0      -1
1      -1
4      -1
5      -1
6      -1
       ..
5717   -1
5718   -1
5719   -1
5720   -1
5721   -1
Name: emotions_, Length: 5095, dtype: int64


In [63]:
print("X_unlabeled",X_unlabeled)


X_unlabeled 0       [fast, shipping, cloth, finally, fit, well, sa...
1       [wanted, say, delighted, friendly, helpful, st...
4       [parcel, never, arrived, chasing, refund, subs...
5       [avoid, ordering, online, ordered, 12, day, ag...
6       [awful, service, returning, item, booked, coll...
                              ...                        
5717    [id, given, 0, star, could, id, known, evri, h...
5718    [wanted, change, delivery, location, item, wit...
5719    [waiting, since, 24142022, believe, sent, orde...
5720    [complain, late, delivery, horrendous, compnay...
5721    [placed, order, 24th, november, h, alert, orde...
Name: tokenized_text, Length: 5095, dtype: object


In [64]:
print("X_labeled",X_labeled)


X_labeled 2       [order, took, 6, day, snow, day, weekend, happ...
3       [wouldnt, give, star, ordered, coat, 4, week, ...
10      [went, h, glasgow, saturday, bought, kid, stuf...
18      [trying, order, product, online, cost, option,...
25                                            [use, evri]
                              ...                        
5692    [dont, order, online, go, store, tooooo, much,...
5695    [h, use, evri, formally, hermes, courier, lost...
5701    [staff, westfield, stratford, rude, went, 2, 5...
5711    [packet, came, weekim, super, satisfiedeveryth...
5715    [received, item, wrong, colour, damaged, conta...
Name: tokenized_text, Length: 627, dtype: object


In [65]:
print(df)

         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
1       ID10          Z_       GB             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
...      ...         ...      ...           ...       ...   
5717   ID995          H_       GB             1       NaN   
5718   ID996          H_       GB             1       NaN   
5719   ID997          H_       CY             1       NaN   
5720   ID998          H_       GB             1       NaN   
5721   ID999          H_       NL             1       NaN   

                                         tokenized_text  
0     [fast, shipping, cloth, finally, fit, well, sa...  
1     [wanted, say, delighted, friendly, helpful, st...  
2     [order, took, 6, day, snow, day, weekend, happ...  
3     [wouldnt, give, star, ordered

In [70]:
## PIPELINE

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.semi_supervised import LabelSpreading
from sklearn.preprocessing import FunctionTransformer

# Parameters
sdg_params = dict(alpha=1e-5, penalty="l2", loss="log_loss")
vectorizer_params = dict(ngram_range=(1, 2), min_df=1, max_df=0.8)

# Supervised Pipeline
pipeline = Pipeline(
    [
        ("vect", CountVectorizer(**vectorizer_params)),
        ("tfidf", TfidfTransformer()),
        ("clf", SGDClassifier(**sdg_params)),
    ]
)

# LabelSpreading Pipeline
ls_pipeline = Pipeline(
    [
        ("vect", CountVectorizer(**vectorizer_params)),
        ("tfidf", TfidfTransformer()),
        # LabelSpreading does not support dense matrices
        ("toarray", FunctionTransformer(lambda x: x.toarray())),
        ("clf", LabelSpreading(kernel='rbf', gamma=20, n_neighbors=7, alpha=0.2, max_iter=30, tol=0.001, n_jobs=None)),
    ]
)

## Define a function for a classification report

In [71]:
def eval_and_print_metrics(clf, X_train, y_train, X_test, y_test):
    print("Number of training samples:", len(X_train))
    print("Unlabeled samples in training set:", sum(1 for x in y_train if x == -1)) #if x == 'NaN'
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    #print("y Train", y_train)
    #print("y Predict",y_pred)
    #print("y Test",y_test)

    print(
        "Micro-averaged F1 score on test set: %0.3f"
        % f1_score(y_test, y_pred, average="micro")
    )
    print("\nConfusion Matrix:\n", confusion_matrix(y_test,y_pred))
    print("\nClassification Report:\n", classification_report(y_test, y_pred,zero_division=1))
    print("\n\n")

In [76]:
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.semi_supervised import LabelSpreading
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

def eval_and_print_metrics(clf, X_train, y_train, X_test, y_test):
    print("Number of training samples:", len(X_train))
    print("Unlabeled samples in training set:", sum(1 for x in y_train if x == -1)) #if x == 'NaN'
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    print(
        "Micro-averaged F1 score on test set: %0.3f"
        % f1_score(y_test, y_pred, average="micro")
    )
    print("\nConfusion Matrix:\n", confusion_matrix(y_test,y_pred))
    print("\nClassification Report:\n", classification_report(y_test, y_pred,zero_division=1))
    print("\n\n")

# Example usage:
# eval_and_print_metrics(pipeline, X_train, y_train, X_test, y_test)


In [85]:
type(y_labeled)

pandas.core.series.Series

## SPLITTING THE DATA 

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X_labeled, y_labeled, test_size=0.2, stratify=y_labeled, random_state=42)

## Supervised SGDClassifier on the labeled data

In [87]:
# Convert lists of tokens to strings
X_train = X_train.apply(lambda x: ' '.join(x))
X_test = X_test.apply(lambda x: ' '.join(x))

# Supervised SGDClassifier on the labeled data
print("Supervised SGDClassifier on the labeled data:")
eval_and_print_metrics(pipeline, X_train, y_train, X_test, y_test)


Supervised SGDClassifier on the labeled data:
Number of training samples: 501
Unlabeled samples in training set: 0
Micro-averaged F1 score on test set: 0.540

Confusion Matrix:
 [[ 4  1  0  1  2  1  2]
 [ 1  7  1  1  1  3  2]
 [ 1  1  8  1  0  3  2]
 [ 0  0  2 13  0  3  2]
 [ 1  1  1  0 13  1  3]
 [ 2  2  0  1  6  8  1]
 [ 0  3  0  1  1  3 15]]

Classification Report:
               precision    recall  f1-score   support

       anger       0.44      0.36      0.40        11
     disgust       0.47      0.44      0.45        16
        fear       0.67      0.50      0.57        16
         joy       0.72      0.65      0.68        20
     neutral       0.57      0.65      0.60        20
     sadness       0.36      0.40      0.38        20
    surprise       0.56      0.65      0.60        23

    accuracy                           0.54       126
   macro avg       0.54      0.52      0.53       126
weighted avg       0.55      0.54      0.54       126






### Label Spreading Algorithm on the labeled and unlabeled data

## Manage Labeled and Unlabeled Data

In [88]:
test_indices = X_test.index
#print("TEST INDICES",test_indices)

# Exclude test data from X_labeled and y_labeled based on the identified indices
X_labeled_filtered = X_labeled.drop(index=test_indices, errors='ignore')
y_labeled_filtered = y_labeled.drop(index=test_indices, errors='ignore')

# Concatenate the filtered labeled data with the unlabeled data
X=X_combined = pd.concat([X_labeled_filtered, X_unlabeled])
y=y_combined = pd.concat([y_labeled_filtered, y_unlabeled])

In [90]:
X_combined.head()

2     [order, took, 6, day, snow, day, weekend, happ...
10    [went, h, glasgow, saturday, bought, kid, stuf...
18    [trying, order, product, online, cost, option,...
25                                          [use, evri]
31    [worst, customer, service, delivery, worse, am...
Name: tokenized_text, dtype: object

In [91]:
y_combined.head()

2          joy
10    surprise
18       anger
25     neutral
31     disgust
Name: emotions_, dtype: object

## MAPPING LABELS 

In [95]:
# Convert tokenized text back to text
X_text = [' '.join(tokens) for tokens in X]
X_test_text = [' '.join(tokens) for tokens in X_test]

# Fit the LabelSpreading pipeline on the combined labeled and unlabeled data
ls_pipeline.fit(X_text, y)

# Predict on the test data
y_pred_ls = ls_pipeline.predict(X_test_text)

# Print evaluation metrics
print("Label Spreading Classifier on the labeled and unlabeled data:")
print("Micro-averaged F1 score on test set:", f1_score(y_test, y_pred_ls, average='micro'))

# Print confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_ls))


Label Spreading Classifier on the labeled and unlabeled data:
Micro-averaged F1 score on test set: 0.18253968253968253

Confusion Matrix:
 [[ 0  0 20  0  0  0  0]
 [ 0  0 16  0  0  0  0]
 [ 0  0 23  0  0  0  0]
 [ 0  0 11  0  0  0  0]
 [ 0  0 20  0  0  0  0]
 [ 0  0 16  0  0  0  0]
 [ 0  0 20  0  0  0  0]]


In [96]:
from sklearn.metrics import classification_report

# Fit the LabelSpreading pipeline on the combined labeled and unlabeled data
ls_pipeline.fit(X_text, y)

# Predict on the test data
y_pred_ls = ls_pipeline.predict(X_test_text)

# Print evaluation metrics
print("Label Spreading Classifier on the labeled and unlabeled data:")
print("Micro-averaged F1 score on test set:", f1_score(y_test, y_pred_ls, average='micro'))

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred_ls))

# Print confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_ls))


Label Spreading Classifier on the labeled and unlabeled data:
Micro-averaged F1 score on test set: 0.18253968253968253

Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00        20
           2       0.00      0.00      0.00        16
           3       0.18      1.00      0.31        23
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00        20
           6       0.00      0.00      0.00        16
           7       0.00      0.00      0.00        20

    accuracy                           0.18       126
   macro avg       0.03      0.14      0.04       126
weighted avg       0.03      0.18      0.06       126


Confusion Matrix:
 [[ 0  0 20  0  0  0  0]
 [ 0  0 16  0  0  0  0]
 [ 0  0 23  0  0  0  0]
 [ 0  0 11  0  0  0  0]
 [ 0  0 20  0  0  0  0]
 [ 0  0 16  0  0  0  0]
 [ 0  0 20  0  0  0  0]]


C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# VISUALISATION 